# Generated by Django 5.2.8 on 2026-05-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
