# Generated by Django 5.2.8 on 2025-12-04 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 12, 4, 20, 21, 55, 820716, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
