# Generated by Django 5.2.8 on 2025-12-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
