# Generated by Django 5.2.8 on 2026-02-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0004_delete_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['date_added'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
